# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('gender', models.CharField(choices=[('male', '\u7537\u6027'), ('female', '\u5973\u6027')], default='male', max_length=6, verbose_name='\u6027\u522b')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606fs',
            },
        ),
    ]
