# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170224_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
